### ISSUE TITLE
graph object has no node

### ISSUE THREAD

**Issue by asirico** [alge24/eigenpooing#3]
when i run the ./run_example.sh, I get the following:

```
Namespace(batch_size=30, bias=True, bmname='ENZYMES', bn=True, clip=2.0, con_final=1, concat=1, datadir='data', device='cpu', dropout=0.5, feat='node-feat', feature_type='default', hidden_dim=128, input_dim=10, lr=0.001, mask=1, max_nodes=130, min_nodes=0, norm='l2', normalize=0, num_classes=6, num_epochs=900, num_gc_layers=5, num_pool_final_matrix=1, num_pool_matrix=1, num_shuffle=10, num_workers=1, out_dir='results', output_dim=128, pool_sizes='10', pred_hidden='256', shuffle=0, test_ratio=0.1, train_ratio=0.8, weight_decay=0.0, with_test=1)
bmname:  ENZYMES
num_classes:  6
batch_size:  30
num_pool_matrix:  1
num_pool_final_matrix:  1
epochs:  900
learning rate:  0.001
num of gc layers:  5
output_dim:  128
hidden_dim:  128
pred_hidden:  256
dropout:  0.5
weight_decay:  0.0
shuffle:  0
Using batch normalize:  True
Using feat:  node-feat
Using mask:  1
Norm for eigens:  l2
With test:  1
Device:  cpu
Files exist, reading from stored files....
Reading file from data/data_preprocessed/ENZYMES/pool_sizes_10_nor_0/
Data loaded!
Using node features
Test ratio:  0.1
Train ratio:  0.8
Num training graphs:  480 ; Num validation graphs:  60 ; Num testing graphs:  60
Number of graphs:  600
Number of edges:  37282
Max, avg, std of graph size:  125 , 32.46 , 14.87
Traceback (most recent call last):
  File "train.py", line 714, in <module>
    main()
  File "train.py", line 709, in main
    benchmark_task_val(prog_args, pred_hidden_dims = pred_hidden_dims, feat = prog_args.feat, device=device)
  File "train.py", line 434, in benchmark_task_val
    prepare_data(graphs, graphs_list, args, test_graphs = None,max_nodes=args.max_nodes, seed = i)
  File "train.py", line 275, in prepare_data
    dataset_sampler = GraphSampler(train_graphs,train_graphs_list, args.num_pool_matrix,args.num_pool_final_matrix,normalize=False, max_num_nodes=max_nodes,
  File "/home/anthony/School/Research/Projects/eigenpooling/graph_sampler.py", line 30, in __init__
    self.feat_dim = G_list[0].node[0]['feat'].shape[0]
AttributeError: 'Graph' object has no attribute 'node'
```
Can you explain the issue? Keep in mind I am an engineer inexperienced in computer science.

**Comment by alge24** [comment]
This is likely caused by the version of networkx. 
You may install networkx with version 2.2 to address this issue.
